"""Which courts are RELEASED through the public API — generated, not typed.

Generated from the reviewer's own marks (`output/notes/marks.json`): a court
is released when EVERY record in its corpus directory has been reviewed and
NONE is marked bad. That is a human judgement about whether the reading is
right, which no grade in this repo can stand in for — `quality` measures
mechanical signals and `status` only says nothing went unaccounted for.

As of 2026-08-21: 176 released, 62 held back
(of 238 courts in the corpus).

Regenerate with `python -m harness.cli released --write` after clearing nays.
The extractor itself is NOT gated: `harness.cli extract`, `render`, the guard
and the viewer all read every court, released or not. This gates one thing —
the front door in `centralia.read`.
"""

from __future__ import annotations

RELEASED: frozenset[str] = frozenset({
    "acca",
    "afcca",
    "akd",
    "ala",
    "alacivapp",
    "alacrimapp",
    "alaska",
    "alaskactapp",
    "almd",
    "alnd",
    "alsd",
    "ared",
    "ariz",
    "arizctapp",
    "ark",
    "arkctapp",
    "armfor",
    "arwd",
    "asbca",
    "azd",
    "bap1",
    "bap10",
    "bap6",
    "bap8",
    "bap9",
    "bia",
    "ca1",
    "ca10",
    "ca11",
    "ca2",
    "ca4",
    "ca5",
    "ca6",
    "ca7",
    "ca8",
    "ca9",
    "cadc",
    "caed",
    "cafc",
    "cal",
    "calag",
    "calctapp",
    "casd",
    "cavc",
    "cit",
    "cod",
    "coloctapp",
    "conn",
    "connappct",
    "dc",
    "dcd",
    "del",
    "delch",
    "delctcompl",
    "delsuperct",
    "fla",
    "fladistctapp",
    "flnd",
    "ga",
    "gactapp",
    "gamd",
    "gand",
    "guam",
    "haw",
    "hawapp",
    "idaho",
    "idahoctapp",
    "idd",
    "ill",
    "illappct",
    "ilsd",
    "ind",
    "indctapp",
    "indtc",
    "innd",
    "iowa",
    "iowactapp",
    "kan",
    "kanctapp",
    "ksd",
    "ky",
    "kyctapp",
    "kyed",
    "la",
    "lactapp",
    "laed",
    "mass",
    "massappct",
    "md",
    "mdag",
    "mdctspecapp",
    "me",
    "mesuperct",
    "mich",
    "michctapp",
    "minn",
    "minnctapp",
    "miss",
    "missctapp",
    "miwd",
    "mo",
    "moctapp",
    "mont",
    "msnd",
    "mspb",
    "nc",
    "ncbizct",
    "ncctapp",
    "nd",
    "ndd",
    "neb",
    "nebctapp",
    "ned",
    "nev",
    "nevapp",
    "nh",
    "nhd",
    "nj",
    "njsuperctappdiv",
    "njtaxct",
    "nm",
    "nmariana",
    "nmcca",
    "nmctapp",
    "nmd",
    "nyfamct",
    "nysurct",
    "ohio",
    "ohioctapp",
    "ohioctcl",
    "ohsd",
    "oked",
    "oknd",
    "okwd",
    "olc",
    "or",
    "orctapp",
    "ortc",
    "pa",
    "pacommwct",
    "pasuperct",
    "ri",
    "sc",
    "scctapp",
    "scd",
    "sd",
    "tax",
    "tenn",
    "tenncrimapp",
    "tennctapp",
    "tex",
    "texapp",
    "texbizct",
    "texcrimapp",
    "tnmd",
    "ttab",
    "txwd",
    "uscfc",
    "uscgcoca",
    "utah",
    "utahctapp",
    "va",
    "vactapp",
    "vaed",
    "vt",
    "vtsuperct",
    "wash",
    "washctapp",
    "wis",
    "wisctapp",
    "wva",
    "wvactapp",
    "wvnd",
    "wvsd",
    "wyd",
    "wyo",
})

# court -> (records, reviewed, marked bad) for the ones still held back.
HELD_BACK: dict[str, tuple[int, int, int]] = {
    "ca3": (103, 103, 1),
    "cacd": (22, 22, 20),
    "cand": (22, 22, 15),
    "ctd": (31, 31, 1),
    "ded": (25, 25, 22),
    "flmd": (22, 22, 4),
    "flsd": (22, 22, 20),
    "gasd": (22, 22, 15),
    "hid": (29, 29, 18),
    "iand": (25, 25, 1),
    "iasd": (10, 10, 1),
    "ilcd": (33, 33, 33),
    "ilnd": (22, 22, 1),
    "insd": (22, 22, 3),
    "kywd": (22, 22, 3),
    "lamd": (33, 6, 2),
    "lawd": (29, 3, 3),
    "mad": (22, 22, 2),
    "mdd": (23, 23, 1),
    "med": (29, 29, 2),
    "mied": (22, 22, 5),
    "minnag": (41, 1, 1),
    "mnd": (22, 22, 5),
    "moed": (22, 22, 1),
    "mowd": (22, 22, 2),
    "mssd": (24, 0, 0),
    "mtd": (29, 0, 0),
    "nced": (23, 0, 0),
    "ncmd": (33, 13, 4),
    "ncwd": (26, 2, 2),
    "njd": (22, 22, 9),
    "nvd": (22, 7, 4),
    "nycivct": (4, 4, 1),
    "nyed": (22, 22, 4),
    "nynd": (24, 24, 9),
    "nysd": (22, 22, 5),
    "nysupct": (21, 16, 0),
    "nywd": (26, 26, 5),
    "ohnd": (25, 25, 1),
    "ord": (22, 6, 6),
    "paed": (22, 22, 1),
    "pamd": (24, 24, 1),
    "pawd": (22, 5, 0),
    "prapp": (42, 0, 0),
    "prsupreme": (31, 1, 1),
    "rid": (25, 25, 1),
    "scotus": (100, 100, 1),
    "sdd": (31, 31, 4),
    "texag": (42, 28, 1),
    "tned": (24, 24, 1),
    "tnwd": (27, 26, 1),
    "txed": (22, 22, 2),
    "txnd": (22, 22, 1),
    "txsd": (22, 22, 1),
    "utd": (23, 23, 1),
    "vawd": (32, 0, 0),
    "virginislands": (32, 32, 3),
    "vtd": (33, 0, 0),
    "waed": (27, 0, 0),
    "wawd": (22, 0, 0),
    "wied": (23, 0, 0),
    "wiwd": (22, 0, 0),
}
