"""Repo-level paths and constants.

The PDF corpus and the review-notes ground truth live in the OLD repo and are
referenced in place — never copied (disk is tight). Everything generated by
this repo lands under OUTPUT_DIR / BASELINE_DIR here.
"""

from __future__ import annotations

import os
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

# --- the old repo, referenced in place -------------------------------------
OLD_REPO = Path(os.environ.get("CENTRALIA_OLD_REPO", "/Users/Palin/Code/centralia"))
CORPUS_ROOT = OLD_REPO / "assets"            # assets/<court>/*.pdf
NOTES_ROOT = OLD_REPO / "output" / "notes"   # per-court .md notes (marks files are stale — ignore)
FOOTNOTE_TRUTH = NOTES_ROOT / "_footnotes_truth.json"

# --- generated by this repo -------------------------------------------------
OUTPUT_DIR = REPO_ROOT / "output"            # review HTML + viewer marks/notes
BASELINE_DIR = REPO_ROOT / "baseline"        # frozen old-system outputs, per court, on demand
MARKS_DIR = OUTPUT_DIR / "notes"             # this repo's own marks/notes (fresh start)


def court_pdfs(court_id: str) -> list[Path]:
    """All corpus PDFs for a court, sorted by stem."""
    d = CORPUS_ROOT / court_id
    if not d.is_dir():
        return []
    return sorted(d.glob("*.pdf"))


def resolve_pdf(name: str) -> Path | None:
    """Resolve `court/stem`, a bare stem, or a path to a corpus PDF."""
    p = Path(name)
    if p.suffix == ".pdf" and p.exists():
        return p
    if "/" in name:
        court, _, stem = name.partition("/")
        cand = CORPUS_ROOT / court / f"{stem.removesuffix('.pdf')}.pdf"
        return cand if cand.exists() else None
    hits = list(CORPUS_ROOT.glob(f"*/{name.removesuffix('.pdf')}.pdf"))
    return hits[0] if len(hits) == 1 else None
