"""Supreme Court of the State of Delaware.

Byline: '<NAME>, <Title>, for the Majority:' / '<NAME>, Justice, dissenting:'
(ends with a colon, and the panel is listed as 'Before SEITZ, Chief Justice;
... Justices, constituting the Court en Banc.'). The module is named
``delaware`` because ``del`` is a Python keyword; the court id stays ``del``.
"""

from __future__ import annotations

import re
from collections import Counter

from ._statesupreme import StateSupreme, is_caps_name

_TAG = re.compile(r"<[^>]+>")
_ROMAN = set("IVXLC")


def _is_section_heading(t: str) -> bool:
    """A centered section heading: a roman numeral + all-caps title
    ('I. INTRODUCTION' / 'V. CONCLUSION'), short and standalone."""
    t = t.strip()
    if not t or len(t) > 50 or t.upper() != t or not any(c.isalpha() for c in t):
        return False
    first = t.split(".", 1)[0].split()[0] if t.split() else ""
    return bool(first) and all(c in _ROMAN for c in first)


class DelawareSupreme(StateSupreme):
    court_id = "del"
    court_label = "Supreme Court of the State of Delaware."
    # This file implements its own richer unsigned-order fallback (a
    # 'Decided:' anchor and caption-footnote bookkeeping the generic base
    # fallback doesn't do) — keep the base one out of the way.
    order_heading_fallback = False
    hm_caption_footnotes = True  # 'TASHA MILLMAN,¹' — caption footnotes
    # The page-number footer sits at y≈726, inside the text margins; fold it
    # out of the body (cross-page merges carry a <pagenumber/> instead).
    fold_page_numbers = True
    # A proposed order carries the court's disposition stamp ('Granted') as a
    # centered bold line at the very top of the page, right on the shared 32pt
    # margin — so the margin filter removed the one word that says what the
    # court DID. Nothing else in the corpus sits in this band except the red
    # e-filing stamp, which ``_is_colored`` removes on its own.
    margin_top = 28

    # Per-document furniture state. Declared at class level so the hooks below
    # stay safe when a caller (the completeness audit) reaches page_lines
    # without going through ``extract``.
    _del_dropped: list = []
    _del_endmatter: list = []
    _del_body_fonts: set = frozenset()
    # A Delaware e-file order can carry a small boxed disposition ('Granted')
    # above the caption. Keep that mark in the extracted headmatter.
    margin_top = 28

    # ------------------------------------------------ e-filing furniture
    @staticmethod
    def _is_colored(line) -> bool:
        """True when a line is printed in coloured ink.

        File & Serve stamps the top margin of the served copy in RED
        ('EFiled: Apr 29 2026 09:55AM EDT / Filing ID … / Case Number …').
        The opinion itself is black throughout, so the ink identifies the
        stamp without reading it."""
        for c in line.get("chars") or []:
            if not (c.get("text") or "").strip():
                continue
            col = c.get("non_stroking_color")
            if isinstance(col, (list, tuple)) and len(col) >= 3:
                if max(col[:3]) - min(col[:3]) > 0.2:
                    return True
        return False

    @staticmethod
    def _line_fonts(line) -> set:
        return {
            (c.get("fontname") or "").split("+")[-1]
            for c in line.get("chars") or []
            if (c.get("text") or "").strip()
        }

    def page_lines(self, page):
        """Lift the e-filing furniture off the document and RECORD it.

        Two artifacts of electronic service, neither of them the court's text:
        the red stamp in page 1's top margin, and — on a multi-case filing —
        a whole trailing page of transaction detail generated by the filing
        system. The detail page gives itself away by sharing NO type with the
        opinion: it is set in the filing system's own faces, so measuring it
        against the document's own body font identifies it whatever the fonts
        happen to be called (Delaware PDFs embed unnamed subsets as often as
        named ones). The stamp is junk (``dropped``); the detail page is real
        trailing matter, so it is kept for the ending-matter section."""
        # The stamp is read off the RAW page: its first row sits above the top
        # text margin, so the margin filter would drop it before it could be
        # recorded and the completeness sweep would then report it unplaced.
        stamp = []
        for c in page.chars:
            col = c.get("non_stroking_color")
            if isinstance(col, (list, tuple)) and len(col) >= 3:
                if max(col[:3]) - min(col[:3]) > 0.2:
                    stamp.append(c)
        rows: list = []  # (top, [chars]) — one printed row per baseline
        for c in sorted(stamp, key=lambda c: (c["top"], c["x0"])):
            if rows and abs(c["top"] - rows[-1][0]) < 4:
                rows[-1][1].append(c)
            else:
                rows.append((c["top"], [c]))
        for _top, cs in rows:
            t = self.line_plain_text({"chars": sorted(cs, key=lambda c: c["x0"])})
            t = " ".join(t.split())
            if t and t not in self._del_dropped:
                self._del_dropped.append(t)

        lines = super().page_lines(page)
        body = [
            l
            for l in lines
            if self.line_plain_text(l).strip() and not self._is_colored(l)
        ]
        if body and not self._del_body_fonts:
            fonts: Counter = Counter()
            for l in body:
                fonts.update(self._line_fonts(l))
            self._del_body_fonts = {f for f, _n in fonts.most_common(3)}
        if body and self._del_body_fonts:
            if not any(self._line_fonts(l) & self._del_body_fonts for l in body):
                self._del_endmatter.extend(self.line_plain_text(l) for l in body)
                return []
        out = []
        for l in lines:
            if self._is_colored(l):
                continue  # already recorded off the raw page above
            text = self.line_plain_text(l).strip()
            if (
                text in (", Justice.", ", Chief Justice.")
                and l.get("x0", 0) > page.width / 2
            ):
                # Blank title line under a proposed-order signature rule.  The
                # actual File & Serve authorization is retained in ending
                # matter; this unfilled form field is template furniture.
                if text not in self._del_dropped:
                    self._del_dropped.append(text)
            out.append(l)
        return out

    def _rail_column_below(self, page, y: float, rail: str = "§") -> int:
        """Rows of the caption's GLYPH RAIL sitting below ``y``.

        A rail is a column: the same glyph repeated at one x. Counting bare
        '§' tokens alone would also count statutory cites in footnote prose
        ('required by § 14(g)'), whose x wanders line to line — so the glyphs
        must agree on a column before they count as a rail."""
        xs: dict = {}
        for w in page.extract_words():
            if (w.get("text") or "").strip() != rail or w["top"] <= y:
                continue
            xs.setdefault(round(w["x0"] / 4.0), []).append(w)
        return max((len(v) for v in xs.values()), default=0)

    def find_footnote_separator(self, page):
        """Reject the divider between two STACKED captions.

        A consolidated appeal prints one caption per case, split by a
        full-width rule (new_castle_county: two captions, the rule at y≈427 on
        a 792pt page). The family separator test only asks for a thin wide rule
        below mid-page anchored at the left margin — which that divider is — so
        it was taken as the footnote separator and the ENTIRE second caption
        became headmatter footnotes.

        The caption's own '§' rail is the discriminator: it continues below a
        stacked-caption divider and cannot appear below a real footnote rule."""
        sep = super().find_footnote_separator(page)
        if sep is not None and self._rail_column_below(page, sep) >= 3:
            return None
        return sep

    def _sweep_residual(self, doc, source_pages) -> None:
        """Surface the e-filing furniture BEFORE the completeness sweep, so it
        is matched against the document instead of reported as unplaced."""
        if self._del_dropped:
            doc.dropped = list(doc.dropped) + self._del_dropped
        if self._del_endmatter:
            doc.trailer = list(doc.trailer) + self._del_endmatter
        super()._sweep_residual(doc, source_pages)

    def extract(self, pdf_path: str):
        """Reclassify roman-numeral section headings ('I. INTRODUCTION') in the
        body as headings so they render centered; type an ORDER's single
        writing as 'order'."""
        self._order_start = None
        self._order_author = None
        self._del_dropped = []
        self._del_endmatter = []
        self._del_body_fonts = set()
        doc = super().extract(pdf_path)
        if self._order_start is not None and doc.opinions:
            doc.opinions[0].type = "order"
        for op in doc.opinions:
            for b in op.blocks:
                if b.kind == "p" and _is_section_heading(_TAG.sub("", b.text)):
                    b.kind = "heading"
        # File & Serve's final metadata panel is a real bordered table. Keep
        # the court's ruling notice in the opinion, but lift the metadata rows
        # into ending matter as a structured table instead of flattened text.
        if doc.opinions:
            import pdfplumber

            with pdfplumber.open(pdf_path) as pdf:
                for page in pdf.pages[1:]:
                    tables = page.find_tables()
                    if not tables:
                        continue
                    rows = tables[0].extract() or []
                    if len(rows) < 2:
                        continue
                    op = doc.opinions[-1]
                    start = next(
                        (
                            i
                            for i, b in enumerate(op.blocks)
                            if (
                                "This document constitutes"
                                in _TAG.sub("", b.text or "")
                                or (
                                    b.page == page.page_number
                                    and _TAG.sub("", b.text or "")
                                    .strip()
                                    .startswith("Court:")
                                )
                            )
                        ),
                        None,
                    )
                    if start is None:
                        continue
                    op.blocks = op.blocks[:start]
                    doc.trailer = list(doc.trailer) + [
                        {"__table__": True, "rows": rows}
                    ]
                    break
        return doc

    # ---------------------------------------------------------- headmatter
    def extract_headmatter(self, headmatter_segs, page1_rules=None) -> dict:
        """Style-preserving headmatter (centered banner, bold rows, relative
        sizes), with the '§'-railed caption folded into a clean two-column
        block — parties on the left of the rail, docket / court-below on the
        right."""
        d = self._styled_headmatter(headmatter_segs, page1_rules)
        d["summary"] = self._fold_rail_caption(d["summary"], "§")
        if not any(
            isinstance(s, dict) and s.get("__caption__") for s in d["summary"]
        ):
            d["summary"] = self._fold_rail_caption(d["summary"], ")")
        # The court banner spans wider than the generic centering cap; it is
        # the page-centered first row of every Delaware caption.
        for s in d["summary"]:
            if isinstance(s, dict) and s.get("__hm__"):
                if _TAG.sub("", s.get("html", "")).startswith(
                    "IN THE SUPREME COURT"
                ):
                    s["align"] = "C"
                break
        return d

    # ------------------------------------------------------------- orders
    def find_authors(self, all_segments) -> list:
        starts = super().find_authors(all_segments)
        self._order_start = None
        if starts:
            return starts
        # No byline: an ORDER. The body starts at the centered 'ORDER'
        # heading — or, on heading-less single-page orders, at the segment
        # after the 'Submitted:/Decided:' caption block — and the author
        # signs '/s/ Name' over a Justice title after 'BY THE COURT:'.
        start = None
        for i, (_p, seg, _k) in enumerate(all_segments):
            if seg and self.line_plain_text(seg[0]).strip().upper().startswith("ORDER"):
                start = i
                break
        if start is None:
            for i, (_p, seg, _k) in enumerate(all_segments):
                if any(
                    self.line_plain_text(l).strip().lower().startswith("decided:")
                    for l in seg
                ):
                    if i + 1 < len(all_segments):
                        start = i + 1
                    break
        if start is None:
            return []
        self._order_start = start
        self._order_author = self._signature_author(all_segments)
        if self.hm_caption_footnotes:
            self._hm_super_labels = self._superscript_labels(
                seg for _, seg, _ in all_segments[:start]
            )
        return [start]

    def _signature_author(self, all_segments):
        """The '/s/ Name' signature (some orders type it '/s Name') over its
        'Justice' / 'Chief Justice' title line."""
        lines = [l for _p, seg, _k in all_segments for l in seg]
        for i, line in enumerate(lines):
            t = self.line_plain_text(line).strip()
            if t.lower().startswith(("/s/", "/s ")):
                name = t[3:].strip()
                if i + 1 < len(lines):
                    nxt = self.line_plain_text(lines[i + 1]).strip()
                    if "justice" in nxt.lower() or "judge" in nxt.lower():
                        return f"{name}, {nxt}"
                return name
        return None

    def split_author_line(self, line):
        if getattr(self, "_order_start", None) is not None:
            # The order start is a heading or the first paragraph, not a
            # byline; the author is the signing Justice.
            return (self._order_author or ""), [line]
        return super().split_author_line(line)

    def classify_document_type(self, all_segments, author_indices, n_pages):
        if getattr(self, "_order_start", None) is not None:
            from ..models import DocType

            return DocType.ORDER
        return super().classify_document_type(all_segments, author_indices, n_pages)

    def _is_non_author_byline(self, text: str) -> bool:
        """A Delaware byline is COLON-TERMINATED — 'LEGROW, Justice:' /
        'SEITZ, Chief Justice, for the Majority:' / 'VAUGHN, Justice,
        dissenting:' — whether it stands alone or opens the paragraph.

        The panel roster ends in a period instead: 'Before SEITZ, Chief
        Justice; VALIHURA, TRAYNOR, LEGROW, and GRIFFITHS, Justices,
        constituting the Court en Banc.' It wraps, and its continuation line
        opens with a bold surname, so it reads as a byline on every cue except
        the terminator — which then opened a phantom opinion holding the
        counsel block."""
        if ":" not in text:
            return True
        return super()._is_non_author_byline(text)

    def parse_author_line(self, text):
        r = super().parse_author_line(text)
        if r is not None:
            return r
        t = text.strip().rstrip(":")
        parts = [p.strip() for p in t.split(",")]
        if len(parts) < 2:
            return None
        name, title = parts[0], parts[1]
        if not is_caps_name(name):
            return None
        if not any(x in title for x in ("Justice", "Judge")):
            return None
        # A PLURAL title is a panel roster, not a byline: the en banc line
        # ('Before SEITZ, Chief Justice; VALIHURA, TRAYNOR, LEGROW, and
        # GRIFFITHS, Justices, constituting the Court en banc.') wraps, and its
        # second line reads as 'NAME, Title, …' exactly like an authored one.
        # Taking it opened a phantom opinion whose 'body' was the counsel
        # block. One writing, one author — 'Justices' names the bench.
        if title.rstrip(".").endswith("s"):
            return None
        kind = ", ".join(parts[2:]).strip() or None
        if kind and "majority" in kind.lower():
            kind = None
        return name, title, kind
