"""Supreme Court of the State of New York ('nysupct').

Everything unique to nysupct lives here. It imports core, never another
court file, and no other court file imports it. Its CourtProfile is
registered in courts/__init__.py; this module adds the reader only, so
importing it can never raise a duplicate profile.

THE CONTRACT — THIS RECORD IS TWO PAPERS, and only the first is this
reader's. Page 1 is the REPORTER'S COVER SHEET, generated by the Law
Reporting Bureau: a ruled box holding one labelled field per band. Page 2
onward is the trial court's own NYSCEF filing, stamp band and all, which is
core's to read like any e-filed paper.

    ┌─ page 1, the boxed cover ──────────────────────────────────────┐
    │ ┌────────────────────────────────────────────────────────────┐ │
    │ │        1200 AOA Realty, LLC v 1200 AOA Realty Assoc.,      │ │ 1-2 rows
    │ │                            LLC                             │ │ THE TITLE
    │ ├────────────────────────────────────────────────────────────┤ │
    │ │                  2026 NY Slip Op 31048(U)                  │ │ THE CITE  <- dispatch
    │ ├────────────────────────────────────────────────────────────┤ │
    │ │                       March 16, 2026                       │ │ +1 date
    │ ├────────────────────────────────────────────────────────────┤ │
    │ │               Supreme Court, New York County               │ │ +2 court
    │ ├────────────────────────────────────────────────────────────┤ │
    │ │          Docket Number: Index No. 650332/2025              │ │ +3 docket
    │ ├────────────────────────────────────────────────────────────┤ │
    │ │                 Judge: Leslie A. Stroth                    │ │ +4 judge
    │ ├────────────────────────────────────────────────────────────┤ │
    │ │ Cases posted with a "30000" identifier … eCourts Service.  │ │ +5 notice
    │ ├────────────────────────────────────────────────────────────┤ │
    │ │ This opinion is uncorrected and not selected for official  │ │    notice
    │ │ publication.                                               │ │
    │ └────────────────────────────────────────────────────────────┘ │
    │ file:///LRB-ALB-FS1/Vol1/ecourts/…  9pt        the Bureau's path│
    └────────────────────────────────────────────────────────────────┘

WHAT CORE DOES WITH IT UNREAD, and why the reader is worth writing. The box
is drawn — four vertical rules (x=160.8, 163.0, 447.2, 449.5) and a
horizontal rule under every band — so `caption_signature` classifies the
page 'backwards-c' with `mid_x` at 447.2, the box's own RIGHT EDGE. Every
row's centre falls left of that, so core reads the cover as EIGHT
two-column caption blocks, each holding one left cell and an empty right
one, separated by eight `Rule`s. No text is lost and nothing is mis-filed
— but not one row carries a role, the two Bureau notices are kept as
caption content rather than dropped, and the whole cover reads as a caption
the court never printed.

THE FIELD GRID IS THE WHOLE READING, and it is fixed. Measured on all 21
records, every offset holds 21/21:

    the cite   '<year> NY Slip Op <number>(U)'   the DISPATCH
    +1         the decision date
    +2         the court and its county
    +3         'Docket Number: …'
    +4         'Judge: …'
    +5         the first Bureau notice

so nothing below the cite is identified by its wording. That matters most
at +2, because THE BUREAU MISSPELLS ITS OWN COURT. Nine of the 21 records
print something other than 'Supreme Court, New York County':

    Supeme Court, New York County       3    Supreme Cour, …            1
    Surpeme Court, New York County      2    Supreme Court, Kiings County   1
    Supreme Court, Rockland Counrty     1    Supreme Court, New York Counrty 1

A reader keyed to the printed string would lose the court on 9 of 21 and,
worse, would lose the OFFSET with it and mis-tint every field below. The
row is taken from its position and checked only for the shape that all 21
share — a comma, then a word ending in the county word, however the Bureau
spelled it. What is RECORDED is the row as printed, misspelling included:
the page is the fact.

THE TITLE IS THE ROWS ABOVE THE CITE — one on 18 records, two on 3, never
more. It is read upward from the dispatch rather than downward from the top
of the box, so a Bureau that adds a band above it cannot shift the reading.

TWO NOTICES, NOT ONE, and both are the Bureau's, not the court's: the
'30000 identifier' republication note and the 'uncorrected and not selected
for official publication' warning. They are `Dropped(kind="notice")`. The
second is also a FACT — it is what makes these records unpublished, which
the '(U)' the cite ends in says a second time — so `publication_status` is
recorded from it and not guessed.

THE SECOND PAPER MUST BE CLAIMED TOO, and finding that out is the lesson of
this port. A court reader's items REPLACE the headmatter whole
(`pipeline.py:1564`), so a claim that stops at the foot of the cover does not
leave page 2's caption where core had it — it re-classifies it as BODY. Read
page 1 alone and the opinion opens on 'SUPREME COURT OF THE STATE OF NEW
YORK', with the two-column caption interleaved into prose ('Plaintiff,
MOTION DATE 09/15/2025'). A partial claim on a two-paper record is worse
than no claim at all.

THE NYSCEF CAPTION, page 2, fenced by the pleading paper's TYPED RULES:

    ┌─ page 2 ───────────────────────────────────────────────────────┐
    │ FILED: NEW YORK COUNTY CLERK …   INDEX NO. …    core's furniture │
    │           SUPREME COURT OF THE STATE OF NEW YORK   13.4pt  court │
    │                     NEW YORK COUNTY                13.4pt  court │
    │ PRESENT:  HON. LESLIE A. STROTH   Justice   PART   12M     bench │
    │                        ----------X          INDEX NO.  650332/…  │ <- fence
    │ 1200 AOA REALTY, LLC,                       MOTION DATE 09/15/…  │
    │              Plaintiff,                     MOTION SEQ. NO. 003  │  the
    │                  -V -                       DECISION + ORDER ON  │  BAND
    │ 1200 AOA REALTY ASSOCIATES, LLC, …          MOTION               │
    │              Defendant.                                          │
    │                     ·-----------X                                │ <- fence
    │ The following e-filed documents … were read on this motion …      │  body
    └──────────────────────────────────────────────────────────────────┘

The band is read as a two-column `CaptionBlock` — the parties on the left,
the Part form's labelled fields on the right — because that is what the page
prints. Joined by visual row instead, the docket lands inside a party name.

THIS PORT IS PARTIAL, AND DELIBERATELY SO. Page 2 is not one form. Measured
over all 21 records, counting the typed rules on page 2:

    2 rules   13   the Part form above — read
    5 rules    1   a venue recital above the band, its rules doubled
    3 rules    1   an 'At an IAS Trial Term …' venue recital above the band
    1 rule     1   no closing fence
    0 rules    5   Kings County's recital form, no typed fence at all

The reader claims only where it can fence the band, and returns NOTHING for
the whole record otherwise — so the 6 unfenced records read EXACTLY as they
did before this file existed. `biz_advance_now` IS fenced and IS read, and it
also has a broken text layer, printing 'the tate of ew York' and 'PRES E T:'
with every N dropped; no reader can fix that, and it is not this one's
business to try.
"""

from __future__ import annotations

import re

from .. import model as m
from ..resolve.footnotes import line_markup
from ..resolve.furniture import FurnitureFinder
from ..resolve.evidence import NOTHING, decider

STYLE_COVER = "reporter cover sheet"

# ---- nysupct's declared facts (measured over all 21 records) -------------
# THE DISPATCH: the Slip Op citation, the one row on the cover whose wording
# is exact on all 21 records. '(U)' is the Reporter's mark for a decision
# not selected for publication, and every record in this corpus carries it.
_CITE = re.compile(r"^(?P<cite>\d{4}\s+NY\s+Slip\s+Op\s+\d+\(U\))$")
# HOW FAR DOWN THE BOX THE DISPATCH MAY SIT. The title above it is 1 row on
# 18 records and 2 on 3; a third would still be found.
_CITE_SEARCH = 4
# THE DATE, as the Bureau sets it: 'March 16, 2026'. Spelled month, never
# abbreviated, on all 21.
_DATE = re.compile(r"^(?:January|February|March|April|May|June|July|August"
                   r"|September|October|November|December)\s+\d{1,2},\s*\d{4}$")
# THE COURT ROW's SHAPE, which is all that may be asked of it — see the
# module docstring on the Bureau's spelling. 'Cour', 'Coun', 'Counrty' and
# 'County' all satisfy it; a labelled field ('Docket Number:', 'Judge:')
# never does, which is what keeps the offset honest if a band is ever added.
# A COUNTY IS NOT ONE WORD. 'New York County' names 12 of the 21 records'
# county in two, and a one-word pattern read only the Kings/Ontario/
# Rockland/Washington records — 6 of 21 claimed.
_COURT_SHAPE = re.compile(r"^(?!Docket Number:|Judge:).*,\s*"
                          r"(?:[A-Z][A-Za-z]*\s+)*Coun\w*\.?$")
_DOCKET = re.compile(r"^Docket\s+Number:\s*(?P<docket>.+?)\.?$")
_JUDGE = re.compile(r"^Judge:\s*(?P<judge>.+?)\.?$")
# THE BUREAU'S TWO NOTICES, each identified by its opening words.
_NOTICE_REPUB = re.compile(r"^Cases\s+posted\s+with\b", re.I)
_NOTICE_UNPUB = re.compile(r"^This\s+opinion\s+is\s+uncorrected\b", re.I)
# THE BUREAU'S OWN FILE PATH, set at 9pt in the bottom margin of the cover
# on 12 of 21 records. Core leaves it in the block; it is the Bureau's
# plumbing and belongs nowhere in the document.
_PATH = re.compile(r"^file:///", re.I)
# 'Kaplan v Kaplan' — the title is the case name, and the pivot the Bureau
# sets is a bare 'v' with no period.
_PIVOT = re.compile(r"\s+v\.?\s+")

# ---- page 2: the court's own NYSCEF paper --------------------------------
# THE PLEADING PAPER'S TYPED FENCE, in every form the corpus prints it:
# '----------X' and '·-----------X' (the Part form), a run of '=' or '-'
# (the Kings recital form). Never a bare hyphen pair, which is how '-V -'
# and '-against-' are set.
# THE CAP IS SOMETIMES A LOWERCASE x. The pleading rule ends '----------X'
# on most records and '----------x' on others — the typist's shift key, not a
# different object. Case-sensitive, the pattern missed the fence on
# `biz_advance_now` and two of `neal_v._extell`'s five rules.
_TYPED_RULE = re.compile(r"^[·•\s]*(?:[-‐-―=_]{6,}|[-‐-―]{3,}\s*[Xx])"
                         r"[·•\s]*[Xx]?\s*$")
# WHO IS SITTING, however the form spaces the word: 'PRESENT:',
# 'P R E S E N T:', and the OCR-mangled 'PRES E T:' all name the bench.
_PRESENT = re.compile(r"^P\s*R\s*E\s*S\s*E?\s*N?\s*T\s*:?", re.I)
# 'HON. LESLIE A. STROTH' / 'Honorable Reginald A. Boddie' — the judge, as
# the form titles them.
_HON = re.compile(r"\b(?:HON\.?|Honorable)\s+(?P<judge>[A-Z][^,]*?)"
                  r"(?:,\s*(?:J\.S\.C\.|Justice)\b.*)?$", re.I)
# THE RIGHT COLUMN'S LABELLED FIELDS. 'INDEX NO.' is this court's docket;
# everything else the Part form stacks there is case apparatus, which is
# what `case-info` is for, and the paper's own name takes `title`.
_R_INDEX = re.compile(r"^Index\s+No\.?:?\s*(?P<docket>[\d/\-]+)?", re.I)
_R_TITLE = re.compile(r"^DECISION\b", re.I)
# ANY of the form's labelled fields — what STOPS a wrapped value.
_LABEL = re.compile(r"^(?:MOTION\s+(?:DATE|SEQ)|Motion\s+Seq|Return\s+Date"
                    r"|Index\s+No|NYSCEF)\b", re.I)
_TITLE_WRAP = re.compile(r"^[A-Z][A-Z\s+&/'’.\-]*$")
# WHERE THE GUTTER IS. The band's right column opens at 374-482pt on the
# Part form and 386 on the recital form; its left column never reaches
# 350. A share of the sheet, not a fixed rail, so a legal-size Part form
# would divide in the same place.
_GUTTER = 0.55


@decider("headmatter.read", court="nysupct")
def read_headmatter_nysupct(model, geom, **_):
    """Read the Reporter's cover sheet on page 1, or NOTHING."""
    if not model.pages:
        return NOTHING
    page1 = model.pages[0]
    body_size = (geom.body_size if geom and geom.body_size else 12.0)
    body_x0 = (geom.body_x0 if geom and geom.body_x0 else 72.0)
    finder = FurnitureFinder(model, body_x0, body_size)

    rows = _rows(page1, finder)
    if len(rows) < 6:
        return NOTHING

    # ---- the dispatch: the Slip Op cite, near the top of the box --------
    cite = at = None
    for idx in range(min(_CITE_SEARCH, len(rows))):
        cite = _CITE.match(_norm(_text(rows[idx])))
        if cite:
            at = idx
            break
    if cite is None:
        return NOTHING
    # The five labelled fields below it must ALL be where the grid says, or
    # this is not the cover this reader measured and core keeps the page.
    if at + 5 >= len(rows):
        return NOTHING
    date = _DATE.match(_norm(_text(rows[at + 1])))
    court = _COURT_SHAPE.match(_norm(_text(rows[at + 2])))
    docket = _DOCKET.match(_norm(_text(rows[at + 3])))
    judge = _JUDGE.match(_norm(_text(rows[at + 4])))
    if not (date and court and docket and judge):
        return NOTHING
    if not _NOTICE_REPUB.match(_norm(_text(rows[at + 5]))):
        return NOTHING

    ctx = _Ctx()
    # ---- the title: every row ABOVE the dispatch ------------------------
    title_rows = [_norm(_text(g)) for g in rows[:at]]
    if not title_rows:
        return NOTHING
    for group in rows[:at]:
        ctx.emit(group, "caption")

    # ---- the five fields, each to the role the cover prints it as -------
    ctx.emit(rows[at], "citation")
    ctx.crit["citation"] = cite.group("cite")
    ctx.emit(rows[at + 1], "date")
    ctx.crit["decision_date"] = _norm(_text(rows[at + 1]))
    # THE ROW AS PRINTED, misspelling and all. Correcting 'Surpeme' here
    # would put a word in the Bureau's mouth; the page is the fact.
    ctx.emit(rows[at + 2], "court")
    ctx.crit["court"] = _norm(_text(rows[at + 2]))
    # 'Index No. 650332/2025' — the index number IS this court's docket.
    ctx.emit(rows[at + 3], "docket")
    ctx.crit["docket_number"] = _norm(docket.group("docket"))
    # ONE JUDGE, NAMED BY THE COVER. A trial court sits alone, so this is an
    # author and never a panel — 21 of 21 name exactly one.
    ctx.emit(rows[at + 4], "author")
    ctx.crit["judges"] = _norm(judge.group("judge"))

    # ---- what is left of the cover is the Bureau's, not the court's -----
    idx = at + 5
    while idx < len(rows):
        text = _norm(_text(rows[idx]))
        if _NOTICE_REPUB.match(text) or _NOTICE_UNPUB.match(text):
            kind = "notice"
            if _NOTICE_UNPUB.match(text):
                # The warning is a fact as well as furniture, and the '(U)'
                # the cite ends in says the same thing.
                ctx.crit["publication_status"] = "unpublished"
        elif _PATH.match(text):
            kind = "stamp"
        elif ctx.dropped and ctx.dropped[-1].kind == "notice":
            # A notice WRAPS ('… not selected for official' / 'publication.')
            # and its continuation is part of it.
            kind = "notice"
        else:
            # NO CATCH-ALL. An unidentified row inside the box would either
            # be mis-tinted or leave a hole in the claim, and both are worse
            # than handing the record back to core whole.
            return NOTHING
        ctx.drop(rows[idx], kind)
        idx += 1

    # ---- the second paper: the court's own NYSCEF caption ---------------
    if len(model.pages) < 2 or not _read_nyscef(ctx, model.pages[1], finder):
        return NOTHING

    ctx.crit["caption"] = title_rows
    _case_name(ctx, title_rows)
    ctx.crit["headmatter_style"] = STYLE_COVER
    return ctx.result()


def _read_nyscef(ctx, pm, finder) -> bool:
    """Page 2's caption, fenced by the pleading paper's typed rules.

    Returns False where the band cannot be fenced — and the caller then
    withdraws the WHOLE claim, cover included, because a claim that ends
    inside the headmatter turns the rest of it into body (see the module
    docstring). Nothing here is keyed to a Part or a county: the fence, the
    gutter and the type size do all the work."""
    rows = _rows(pm, finder)
    # THE FENCE IS A CELL, NOT A ROW. The Part form sets its opening
    # '----------X' on the SAME printed line as the first right-column field
    # ('----------X   INDEX NO.   650332/2025'), so a fence looked for in the
    # joined row text was found on 4 records of 21 instead of 14.
    fence = [i for i, g in enumerate(rows)
             if any(_TYPED_RULE.match(_norm(l.plain)) for l in g)]
    if len(fence) < 2:
        return False
    top, bottom = fence[0], fence[-1]
    if bottom - top < 2:
        return False        # a fence with nothing between it is not a band

    # ---- above the fence: the court naming itself, and the bench --------
    for group in rows[:top]:
        text = _norm(_text(group))
        if _PRESENT.match(text):
            # ONE ROW, THE WHOLE BENCH LINE. The form sets 'PRESENT:', the
            # judge, their title and the Part as separate cells of one
            # printed line, and it renders as the line the page prints.
            ctx.emit(group, "author", centre=False)
            hon = _HON.search(text)
            if hon:
                ctx.crit.setdefault("judges", _norm(hon.group("judge")))
            continue
        # The venue recital ('At an IAS Trial Term, Part 75 of the Supreme
        # Court of the State of New York, Kings County, …') and the Part
        # form's two centred rows are the same fact: the court, as it names
        # itself on its own paper.
        ctx.emit(group, "court", centre=False)

    # ---- the band: parties left, the form's fields right ---------------
    # The fence's own cells are the rail; whatever else stands on the
    # fence's line is the band's first (or last) field.
    mid = pm.width * _GUTTER
    left: list = []
    right: list = []
    for group in rows[top:bottom + 1]:
        rail = [l for l in group if _TYPED_RULE.match(_norm(l.plain))]
        if rail:
            ctx.drop(rail, "rail")
        group = [l for l in group if l not in rail]
        if not group:
            continue
        l_cells = [l for l in group if l.x0 < mid]
        r_cells = [l for l in group if l.x0 >= mid]
        left.append(_cells(l_cells, "caption") if l_cells else _blank(pm))
        right.append(_cells(r_cells, _right_role(r_cells)) if r_cells
                     else _blank(pm))
        for cell in r_cells:
            text = _norm(cell.plain)
            index = _R_INDEX.match(text)
            if index and index.group("docket"):
                # The index number on the court's own paper, which the cover
                # already gave as 'Index No. …' — the same fact twice, so
                # the cover's form is the one kept.
                ctx.crit.setdefault("lower_court_docket", []).append(
                    _norm(index.group("docket")))
            elif _R_TITLE.match(text):
                # THE PAPER'S NAME WRAPS: the Part form sets 'DECISION +
                # ORDER ON' over 'MOTION' in the same right column, and the
                # label alone reads as a sentence cut in half.
                # The wrap is not always the NEXT row: a party row with no
                # right cell can stand between 'DECISION + ORDER ON' and
                # 'MOTION' (4 of the 14 records), so a blank right side is
                # skipped rather than treated as the end of the value. Two
                # at most — past that the next right cell belongs to
                # something else.
                title = text
                blanks = 0
                for after in rows[rows.index(group) + 1:bottom + 1]:
                    tail = [_norm(c.plain) for c in after if c.x0 >= mid]
                    if not tail:
                        blanks += 1
                        if blanks > 2:
                            break
                        continue
                    piece = " ".join(tail).strip()
                    # THE WRAP IS SET LIKE THE NAME IT CONTINUES: capitals,
                    # no numerals. Anything else in that column is another
                    # field — a party's 'Third-Party' cell, or a label this
                    # record's broken text layer prints as 'Index o.' with
                    # the N dropped, which no label pattern can catch.
                    if not _TITLE_WRAP.match(piece):
                        break
                    title = title.rstrip() + " " + piece
                    blanks = 0
                ctx.crit.setdefault("title", _norm(title))
        ctx.consumed.update(l.id for l in group)
    if not any(r.text.strip() for r in left):
        return False        # no parties: this is not the caption band
    ctx.items.append(m.CaptionBlock(
        left=left, right=right, rail=None,
        prov=m.Prov(pm.number, tuple(
            l.id for g in rows[top:bottom + 1] for l in g))))
    return True


def _right_role(cells: list) -> str:
    """What the Part form's right column is saying on this row. Each field by
    its own label; a row that only continues the value above it keeps
    `case-info`, which is what the column carries whenever it is neither the
    index number nor the paper's name."""
    text = _norm(" ".join(c.plain for c in cells))
    if not text:
        return "caption"
    if _R_INDEX.match(text):
        return "docket"
    if _R_TITLE.match(text):
        return "title"
    return "case-info"


def _cells(cells: list, role: str) -> m.HmLine:
    """One side of a band row: ALL of its cells, left to right. Taking only
    the first would drop a label from its value ('Index No.:' / '512674/2021'
    are two cells of one field)."""
    parts = sorted(cells, key=lambda l: l.x0)
    text = ""
    for part in parts:
        piece = line_markup(part)
        text = (text.rstrip() + "  " + piece.lstrip()) if text.strip() \
            else piece
    first = parts[0]
    return m.HmLine(
        text=text, prov=m.Prov(first.page, tuple(p.id for p in parts)),
        align=m.Align.LEFT, x0=first.x0, size=first.size or 0.0,
        bold=all(bool(p.all_bold) for p in parts), role=role)


def _blank(pm, role: str = "caption") -> m.HmLine:
    """EVERY CELL CARRIES A ROLE, blanks included — an untagged row is one
    nothing read, and the two-column ports written before this one (ca6, pa,
    va, mdctspecapp) tag 100% of their block."""
    return m.HmLine(text="", prov=m.Prov(pm.number), role=role)


def _case_name(ctx, title_rows: list[str]) -> None:
    """The title is the case name, wrapped mid-phrase on the 3 records that
    need two rows ('1200 AOA Realty, LLC v 1200 AOA Realty Assoc.,' /
    'LLC'). Joined on a space, and split on the pivot only where the title
    holds exactly one — nothing is invented from a title that holds none."""
    whole = " ".join(title_rows).strip()
    if not whole:
        return
    ctx.crit["case_name"] = whole
    parts = _PIVOT.split(whole)
    if len(parts) == 2:
        ctx.crit["parties"] = [p.strip(" ,.") for p in parts if p.strip(" ,.")]


def _norm(text: str) -> str:
    return " ".join(text.split())


def _text(group: list) -> str:
    return " ".join(l.plain for l in sorted(group, key=lambda l: l.x0))


def _rows(pm, finder) -> list[list]:
    """The page's own visual rows, furniture removed — one entry per band of
    the box, its cells left to right."""
    groups: dict = {}
    order: list = []
    for line in sorted(pm.lines, key=lambda l: (l.top, l.x0)):
        if not line.plain.strip() or finder.kind(pm, line):
            continue
        key = round(line.top, 1)
        if key not in groups:
            groups[key] = []
            order.append(key)
        groups[key].append(line)
    return [groups[k] for k in order]


class _Ctx:
    """The emit buffer: what the walk placed, and where it came from."""

    def __init__(self):
        self.items: list = []
        self.dropped: list = []
        self.consumed: set[int] = set()
        self.crit: dict = {}

    def emit(self, group: list, role: str, centre: bool = True) -> None:
        parts = sorted(group, key=lambda l: l.x0)
        if not parts:
            return
        first = parts[0]
        text = ""
        for part in parts:
            piece = line_markup(part)
            text = (text.rstrip() + " " + piece.lstrip()) if text.strip() \
                else piece
        self.items.append(m.HmLine(
            text=text, prov=m.Prov(first.page, tuple(p.id for p in parts)),
            align=m.Align.CENTER if centre else m.Align.LEFT,
            x0=first.x0, size=first.size or 0.0,
            bold=all(bool(p.all_bold) for p in parts), role=role))
        self.consumed.update(p.id for p in parts)

    def drop(self, group: list, kind: str) -> None:
        parts = sorted(group, key=lambda l: l.x0)
        self.dropped.append(m.Dropped(
            text=_norm(" ".join(p.plain for p in parts))[:400],
            prov=m.Prov(parts[0].page, tuple(p.id for p in parts)),
            kind=kind or "furniture"))
        self.consumed.update(p.id for p in parts)

    def result(self) -> dict:
        return {"criteria": self.crit, "items": self.items, "attorneys": [],
                "dropped": self.dropped, "consumed": self.consumed,
                "anchor_ids": [], "doc_type_final": None}
